server {
  listen 80;
  resolver 127.0.0.11 ipv6=off valid=10s;
  resolver_timeout 5s;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header X-Frame-Options "DENY" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Content-Security-Policy "default-src 'self'; img-src 'self' data: https:; media-src 'self' https:; script-src 'self'; style-src 'self' 'unsafe-inline'" always;

  location /api/ {
    set $backend_upstream http://backend:8000;
    proxy_pass $backend_upstream/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    set $frontend_upstream http://frontend:3000;
    proxy_pass $frontend_upstream;
    proxy_set_header Host $host;
  }
}
